- name: enable filebeat
  ansible.builtin.systemd:
    name: filebeat.service
    enabled: yes

- name: start filebeat
  ansible.builtin.systemd:
    name: filebeat.service
    state: started


- name: restart filebeat
  ansible.builtin.systemd:
    name: filebeat.service
    state: restarted