- name: restart node exporter
  systemd:
      name: node-exporter
      state: started

- name: daemon reload
  systemd:
    daemon_reload: yes

- name: enable node-exporter
  systemd:
    name: node-exporter
    enabled: yes
    masked: no
    
