[bastion]
89.169.156.135

[prometheus_server]
10.0.1.20
[prometheus_server:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@89.169.156.135"'


[grafana_server]
10.0.1.24
[grafana_server:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@89.169.156.135"'


[elasticsearch_server]
10.0.1.16
[elasticsearch_server:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@89.169.156.135"'


[kibana_server]
10.0.1.31
[kibana_server:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@89.169.156.135"'






 

[webservers]
10.0.1.29
10.0.2.11
[webservers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@89.169.156.135"'
