[bastion]
84.201.175.241

[prometheus_server]
10.0.1.25
[prometheus_server:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@84.201.175.241"'


[grafana_server]
10.0.1.18
[grafana_server:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@84.201.175.241"'


[elasticsearch_server]
10.0.1.20
[elasticsearch_server:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@84.201.175.241"'


[kibana_server]
10.0.1.17
[kibana_server:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@84.201.175.241"'

  
[webservers]
10.0.1.5
10.0.2.34
[webservers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@84.201.175.241"'
