[bastion]
158.160.55.172

[prometheus_server]
10.0.1.10
[prometheus_server:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@158.160.55.172"'


[grafana_server]
10.0.1.31
[grafana_server:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@158.160.55.172"'


[elasticsearch_server]
10.0.1.6
[elasticsearch_server:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@158.160.55.172"'


[kibana_server]
10.0.1.13
[kibana_server:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@158.160.55.172"'

  
[webservers]
10.0.1.15
10.0.2.24
[webservers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@158.160.55.172"'
