- name: restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
    
      

- name: start grafana
  ansible.builtin.systemd:
    state: started
    name: grafana-server

- name: enable grafana
  ansible.builtin.systemd:
    name: grafana-server
    enabled: yes